### PR TITLE
Added QueryResult.to fn

### PR DESCRIPTION
**Pull request by richard-powers**
I've been using this function to copy row data into an actual struct, and thought it may be useful to have in the library.

Feel free to modify or request modifications, this is just pulled directly from an internal work project.

### CODE REVIEW

**Comment by zigster64** [comment]
Nice !  

One small observation - the Result object has a ptr to an internal arena allocator that is lifecycled over the stamement execution.

It would be possible to drop the Allocator param, let the result dupe values using its own arena, and then everything gets cleaned up automatically when the statement is complete  (no need to free all those dupes anymore at the callsite)

Will try that out here and see if it works the way I think it does

**Comment by karlseguin** [comment]
I'm going to tweak this in a follow up commit.

**Comment by karlseguin** [comment]
I guess the fancier follow up would be

1 - Supporting arrays
2 - Adding a `map` option to `ToOpts`  which can either be `ordinal` or `name`. `ordinal` would be the current logic.  `name` would map based on the field names, using `getCol` instead of `get`

**Comment by zigster64** [comment]
It’s not unusual to have fields in the target struct that you want to skip as well, if they are not in the row

there is a discussion on discord zig-help about providing meta data in the target struct to assist mapping (sort of like go struct tags)

**Comment by karlseguin** [comment]
There's now a `.{.map = .name}` option. The default is `.{.map = .ordinal}`. When using `.name` , the `column_names = true` option must be specified in the `queryOpts` or `rowOpts` functions.

Columns with no field equivalent are ignored. Fields with no column equivalent are set to their default value. If there is no default value, `to` will return an `error.FieldColumnMismatch`.

There's overhead to using `.{.map = .name}`, since the name -> index has to be looked up. When done in a loop (when iterating through a result), it's better to create a mapper and iterate through it:

```zig
var result  = try conn.queryOpts("select....", .{}, .{.column_names = true});
defer result.deinit();

// this takes the same `dupe` and `allocator` opts as `row.to`
var mapper = result.mapper(User, .{});
while (try mapper.next()) |user| {
   // you have a user
}
```

**Pull request merged**
